name: My First GitHub Actions Testing:3

on:
  workflow_dispatch:
jobs:
  Projrct-tag:
    name: Projrct-tag1
    runs-on: ubuntu-latest
    env:  # Define environment variables
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want t

      - name: Install 'hub' command
        run: |
          # Install 'hub' to interact with GitHub via CLI
          # Replace 'YOUR_GITHUB_USERNAME' with your actual GitHub username
          # GitHub Actions provides GITHUB_ACTOR environment variable with the username
          # to get the user who triggered the workflow.
          wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar xvf hub-linux-amd64-2.14.2.tgz
          sudo ./hub-linux-amd64-2.14.2/install

      - name: Set up Git
        run: |
            git config --global user.name "pkj1993"
            git config --global user.email "pkj161293@gmail.com"
            git config --global hub.protocol https

      - name: Fetch the latest tag
        id: fetch_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "")
          echo "Latest tag: $latest_tag"
             
          echo "::set-output name=latest_tag::$latest_tag" 

      - name: Execute Python script for Semantic Versioning
        run: |
             echo "::set-output name=latest_tag::$latest_tag" 
             python ./.github/workflows/semantic_versioning.py ${{ steps.fetch_tag.outputs.latest_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.secrets.PAT }}        
          
        
        
